zend_extension=xdebug.so
xdebug.mode=debug
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
#xdebug.start_with_request=yes
xdebug.idekey=VSCODE
#xdebug.log=/var/log/xdebug.log
#xdebug.output_dir=/var/www/html/devmyproject/pub/var/log/xdebug